[package]
name = "flowbuilder"
version = "0.0.2"
edition = "2021"
description = "An async flow orchestration framework with conditional execution and context sharing."
authors = ["Thne"]
keywords = ["flow", "workflow", "async", "rust"]
readme = "../README.md"
license = "Apache-2.0"
repository = "https://github.com/ThneS/flowbuilder.git"

[dependencies]
flowbuilder-core = { path = "../flowbuilder-core" }
flowbuilder-macros = { path = "../flowbuilder-macros", optional = true }
flowbuilder-context = { path = "../flowbuilder-context" }
flowbuilder-logger = { path = "../flowbuilder-logger", optional = true }
flowbuilder-runtime = { path = "../flowbuilder-runtime", optional = true }

# Re-export workspace dependencies
anyhow = { workspace = true }
tokio = { workspace = true }

[features]
default = ["core"]
core = ["flowbuilder-core/default"]
macros = ["dep:flowbuilder-macros", "flowbuilder-core/macros"]
logger = ["dep:flowbuilder-logger", "flowbuilder-core/logger"]
runtime = ["dep:flowbuilder-runtime", "flowbuilder-core/runtime"]
full = ["macros", "logger", "runtime"]

# Legacy features for backwards compatibility
mvp = ["core"]
strong = ["logger"]
