# Issue 模板配置
# 用于自定义 Issue 创建流程

name: Issue 模板
description: 请选择合适的模板来创建 Issue
body:
  - type: markdown
    attributes:
      value: |
        感谢您对 FlowBuilder 项目的关注！请选择合适的模板来创建 Issue。
        如果您想报告安全漏洞，请使用安全漏洞报告链接。
        对于一般性讨论，请使用讨论区。

  - type: checkboxes
    attributes:
      label: 联系链接
      description: 请选择您需要的 Issue 类型
      options:
        - label: 安全漏洞报告
          required: false
        - label: 功能请求
          required: false
        - label: 文档问题
          required: false
        - label: Bug 报告
          required: false
        - label: 社区讨论
          required: false

blank_issues_enabled: false
contact_links:
  - name: 安全漏洞报告
    url: https://github.com/ThneS/flowbuilder/security/advisories/new
    about: 请使用此链接报告安全漏洞，不要创建公开 Issue

  - name: 功能请求
    url: https://github.com/ThneS/flowbuilder/issues/new?template=feature_request.md
    about: 请使用功能请求模板提出新功能建议

  - name: 文档问题
    url: https://github.com/ThneS/flowbuilder/issues/new?template=documentation.md
    about: 请使用文档问题模板报告文档问题

  - name: Bug 报告
    url: https://github.com/ThneS/flowbuilder/issues/new?template=bug_report.md
    about: 请使用 Bug 报告模板报告问题

  - name: 社区讨论
    url: https://github.com/ThneS/flowbuilder/discussions
    about: 在讨论区进行一般性讨论