[package]
name = "flowbuilder-macros"
version = "0.0.2"
edition = "2021"
description = "Procedural macros for FlowBuilder"
authors = ["Thne"]
license = "Apache-2.0"

[lib]
proc-macro = true

[dependencies]
proc-macro2 = { workspace = true }
quote = { workspace = true }
syn = { workspace = true }
